### ISSUE TITLE
support recent nightly to get better debug info on no_std issues

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#161]
The following rust-lang PR should give us better debug info for `duplicate lang item`issues:

Issue:
https://github.com/rust-lang/rust/issues/60561

PR:
https://github.com/rust-lang/rust/pull/64883

Can we get support for recent nightly including this PR?

**Comment by dingelish** [comment]
Hey @brenzi , I figured out a way to use the latest compiler. Please see the branch "test-2019-10". To use that in your enclave, you can add a patch section with fixed path:

```toml
[patch.'https://github.com/baidu/rust-sgx-sdk.git']
sgx_alloc = { path = "../../../ding/rust-sgx-sdk/sgx_alloc" }
sgx_build_helper = { path = "../../../ding/rust-sgx-sdk/sgx_build_helper" }
sgx_cov = { path = "../../../ding/rust-sgx-sdk/sgx_cov" }
sgx_crypto_helper = { path = "../../../ding/rust-sgx-sdk/sgx_crypto_helper" }
sgx_libc = { path = "../../../ding/rust-sgx-sdk/sgx_libc" }
sgx_rand = { path = "../../../ding/rust-sgx-sdk/sgx_rand" }
sgx_rand_derive = { path = "../../../ding/rust-sgx-sdk/sgx_rand_derive" }
sgx_serialize = { path = "../../../ding/rust-sgx-sdk/sgx_serialize" }
sgx_serialize_derive = { path = "../../../ding/rust-sgx-sdk/sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../../ding/rust-sgx-sdk/sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../../ding/rust-sgx-sdk/sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../../ding/rust-sgx-sdk/sgx_tcrypto_helper" }
sgx_tdh = { path = "../../../ding/rust-sgx-sdk/sgx_tdh" }
sgx_tkey_exchange = { path = "../../../ding/rust-sgx-sdk/sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../../ding/rust-sgx-sdk/sgx_tprotected_fs" }
sgx_trts = { path = "../../../ding/rust-sgx-sdk/sgx_trts" }
sgx_tse = { path = "../../../ding/rust-sgx-sdk/sgx_tse" }
sgx_tseal = { path = "../../../ding/rust-sgx-sdk/sgx_tseal" }
sgx_tservice = { path = "../../../ding/rust-sgx-sdk/sgx_tservice" }
sgx_tstd = { path = "../../../ding/rust-sgx-sdk/sgx_tstd" }
sgx_tunittest = { path = "../../../ding/rust-sgx-sdk/sgx_tunittest" }
sgx_types = { path = "../../../ding/rust-sgx-sdk/sgx_types" }
sgx_ucrypto = { path = "../../../ding/rust-sgx-sdk/sgx_ucrypto" }
sgx_unwind = { path = "../../../ding/rust-sgx-sdk/sgx_unwind" }
sgx_urts = { path = "../../../ding/rust-sgx-sdk/sgx_urts" }
```
